{% set name = "matrix2tab" %}
{% set version = "1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source: 
  path: ../src

requirements:
  host:
    - perl
  run:
    - perl

about:
  home: https://github.com/bidauxpoto/matrix2tab.git
  summary: Convert matrix to table
